/*
====================================================================
Project  : End-to-End Olist E-commerce Sales Analysis
Author   : Rajesh Kumar
Role     : Data Analyst
Database : MySQL

Module   : Business Analysis

Description:
This file contains key business KPI analysis queries
used to measure sales performance and business growth.

Business Objective:
To analyze revenue performance, customer spending,
and monthly sales trends for business decision-making.

====================================================================
*/


-- ================================================================
-- Query 1 : Total Revenue
-- ================================================================

/*
Business Question:
What is the total revenue generated by the business?
*/

SELECT
ROUND(SUM(payment_value),2) AS Total_Revenue
FROM order_payments;

/*
Result:
Total Revenue : 16,008,872.12 BRL

Business Insight:
The marketplace generated approximately
16.01 million BRL in total revenue during
the analysis period.
*/


-- ================================================================
-- Query 2 : Average Order Value (AOV)
-- ================================================================

/*
Business Question:
What is the average amount spent per order?
*/

SELECT
ROUND(
SUM(payment_value)
/ COUNT(DISTINCT order_id)
,2) AS Average_Order_Value
FROM order_payments;

/*
Result:
Average Order Value : 160.99 BRL

Business Insight:
On average, customers spent approximately
161 BRL per order.
*/


-- ================================================================
-- Query 3 : Monthly Revenue Trend
-- ================================================================

/*
Business Question:
How has monthly revenue changed over time?
*/

SELECT
DATE_FORMAT(o.order_purchase_timestamp,'%Y-%m') AS Month,
ROUND(SUM(op.payment_value),2) AS Revenue
FROM orders_new o
JOIN order_payments op
ON o.order_id = op.order_id
GROUP BY Month
ORDER BY Month;

/*
Business Insight:

Revenue showed strong growth throughout
2017 and the first half of 2018.

Highest Monthly Revenue:
April 2018 → 1.16 Million BRL

Note:
The sharp decline in September and October 2018
is due to incomplete data availability,
not an actual business decline.
*/


-- ================================================================
-- Query 4 : Monthly Order Trend
-- ================================================================

/*
Business Question:
How many orders were placed each month?
*/

SELECT
DATE_FORMAT(order_purchase_timestamp,'%Y-%m') AS Month,
COUNT(DISTINCT order_id) AS Total_Orders
FROM orders_new
GROUP BY Month
ORDER BY Month;

/*
Business Insight:

Monthly orders increased consistently
during 2017 and reached their peak
during 2018.

The final months (Sep-Oct 2018)
contain incomplete records.
*/


-- ================================================================
-- Query 5 : Monthly Average Order Value
-- ================================================================

/*
Business Question:
How did Average Order Value change over time?
*/

SELECT
DATE_FORMAT(o.order_purchase_timestamp,'%Y-%m') AS Month,

ROUND(
SUM(op.payment_value)
/
COUNT(DISTINCT o.order_id)
,2) AS Average_Order_Value

FROM orders_new o
JOIN order_payments op
ON o.order_id = op.order_id

GROUP BY Month
ORDER BY Month;

/*
Business Insight:

Average Order Value remained relatively stable
between 150 and 170 BRL
throughout most of the analysis period.

This indicates consistent customer spending behavior.

September 2018 shows an unusually high AOV
because the dataset contains only a small
number of orders for that month.
*/


/*
====================================================================

Business Analysis Summary

• Total Revenue : 16.01 Million BRL
• Average Order Value : 160.99 BRL
• Revenue increased steadily during 2017–2018.
• Monthly orders showed continuous business growth.
• Customer spending remained stable over time.

Conclusion:

The Olist marketplace experienced
consistent business growth with
stable customer purchasing behavior.

====================================================================
*/
