/*
====================================================================
Project   : End-to-End Olist E-commerce Sales Analysis
Author    : Rajesh Kumar
Portfolio : Data Analyst Portfolio Project
Tools     : MySQL, Microsoft Excel, Power BI

Module    : KPI Analysis

Description:
This file contains SQL queries used to calculate key
business performance indicators (KPIs) for reporting
and dashboard development.

Business Objective:
To measure the overall performance of the business
using important KPIs that support business decisions.

====================================================================
*/


-- ================================================================
-- Query 1 : Total Revenue
-- ================================================================

/*
Business Question:
What is the total revenue generated by the business?
*/

SELECT
ROUND(SUM(payment_value),2) AS Total_Revenue
FROM order_payments;

/*
Result:

Total Revenue : 16,008,872.12 BRL

Business Insight:

The business generated over
16 million BRL in total revenue
during the analysis period.
*/



-- ================================================================
-- Query 2 : Total Orders
-- ================================================================

/*
Business Question:
How many orders were placed?
*/

SELECT
COUNT(*) AS Total_Orders
FROM orders_new;

/*
Result:

Total Orders : 99,441

Business Insight:

The platform successfully processed
99,441 customer orders.
*/



-- ================================================================
-- Query 3 : Total Customers
-- ================================================================

/*
Business Question:
How many customers placed orders?
*/

SELECT
COUNT(*) AS Total_Customers
FROM customers;

/*
Result:

Total Customers : 99,441

Business Insight:

The dataset contains
99,441 unique customers.
*/



-- ================================================================
-- Query 4 : Total Sellers
-- ================================================================

/*
Business Question:
How many sellers are available on the platform?
*/

SELECT
COUNT(*) AS Total_Sellers
FROM sellers;

/*
Result:

Total Sellers : 3,095

Business Insight:

More than three thousand sellers
actively contributed to marketplace sales.
*/



-- ================================================================
-- Query 5 : Total Products
-- ================================================================

/*
Business Question:
How many products are listed?
*/

SELECT
COUNT(*) AS Total_Products
FROM products;

/*
Result:

Total Products : 32,340

Business Insight:

The marketplace offers
32,340 different products
across multiple categories.
*/



-- ================================================================
-- Query 6 : Average Order Value (AOV)
-- ================================================================

/*
Business Question:
What is the average order value?
*/

SELECT
ROUND(
SUM(payment_value)
/COUNT(DISTINCT order_id)
,2) AS Average_Order_Value
FROM order_payments;

/*
Result:

Average Order Value : 160.99 BRL

Business Insight:

On average,
each customer order generated
160.99 BRL in revenue.
*/



-- ================================================================
-- Query 7 : Average Delivery Time
-- ================================================================

/*
Business Question:
How many days does delivery take on average?
*/

SELECT

ROUND(
AVG(
DATEDIFF(
order_delivered_customer_date,
order_purchase_timestamp
)
),2) AS Avg_Delivery_Days

FROM orders_new

WHERE order_delivered_customer_date IS NOT NULL;

/*
Result:

Average Delivery Time : 12.50 Days

Business Insight:

Orders were delivered
within an average of
12.50 days after purchase.
*/



-- ================================================================
-- Query 8 : Delivery Success Rate
-- ================================================================

/*
Business Question:
What percentage of orders were successfully delivered?
*/

SELECT

ROUND(

SUM(

CASE

WHEN order_status='delivered'

THEN 1

ELSE 0

END

)

*100

/

COUNT(*)

,2) AS Delivery_Success_Rate

FROM orders_new;

/*
Result:

Delivery Success Rate : 97.02%

Business Insight:

More than 97% of all orders
were successfully delivered,
indicating strong operational performance.
*/



/*
====================================================================

KPI Analysis Summary

• Total Revenue             : 16,008,872.12 BRL
• Total Orders              : 99,441
• Total Customers           : 99,441
• Total Sellers             : 3,095
• Total Products            : 32,340
• Average Order Value       : 160.99 BRL
• Average Delivery Time     : 12.50 Days
• Delivery Success Rate     : 97.02%

Conclusion:

The Olist marketplace demonstrated
strong business performance with
high revenue, consistent order volume,
efficient delivery operations,
and a high order fulfillment rate.

====================================================================
*/
